version: "3.9"

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:sample
    build:
      context: ./Dockerfiles/
      dockerfile: nginx.Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    command: nginx -g "daemon off;"

  fastapi:
    container_name: fastapi
    hostname: fastapi
    image: fastapi:sample
    build:
      context: ./Dockerfiles/
      dockerfile: fastapi.Dockerfile
    volumes:
      - ./volumes/fastapi/:/workspace/
    command: uvicorn main:app --reload --host=0.0.0.0 --port=4001

  flutter:
    container_name: flutter
    hostname: flutter
    image: flutter:sample
    build:
      context: ./Dockerfiles/
      dockerfile: flutter.Dockerfile
    volumes:
      - ./volumes/flutter/:/workspace/project/lib/
    command: flutter run -d web-server --web-hostname 0.0.0.0 --web-port 4001

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongodb:sample
    build:
      context: ./Dockerfiles/
      dockerfile: mongodb.Dockerfile 
    tty: true
    stdin_open: true
    volumes:
      - ./volumes/mongodb:/workspace
    command: mongod -f /workspace/mongod.conf